# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
<<<<<<< HEAD
<<<<<<< HEAD:Dhruv/pipelines-dotnet-core-master/azure-pipelines.yml
    projects: 'dhruv/**/*.csproj'
=======
    projects: '**/*.csproj'
>>>>>>> 15e5ba72a1b7817f3508cc15da517a81ce7826e6:Dhruv/azure-pipelines-1.yml
=======
    projects: 'Dhruv/**/*.csproj'
>>>>>>> 15e5ba72a1b7817f3508cc15da517a81ce7826e6
