# Starter Terraform pipeline
# Start with a minimal Terraform pipeline that you can customize to build and deploy your infrastructure.

# Change the pipeline name
name: terraform-Dhruv-pipeline

variables:
  - name: ServiceConnection
    value: padawans-azure

# Customize paths:include: to only detect changes in your folder
trigger:
  branches:
    include:
      - master
      #- Dhruv_Terraform
  paths:
    include: 
      - Dhruv/terraform

pool:
  vmImage: ubuntu-latest

steps:

# (1) Create a 'Install Terraform' task
# Parameters:
# - Version = 1.0.1
- task: TerraformInstaller@0
  displayName: 'Mario Install'
  inputs:
    terraformVersion: '1.0.1'

# (2) Create a 'Terraform Init' task
# Parameters:
# - Azure Subscription = padawans-azure
# - Resource Group: gft-rg-padawans
# - Storage Account: gftstpadawantfstate
# - Storage Container: tfstate
# - Key: - task: TerraformTaskV2@2
- task: TerraformTaskV2@2
  displayName: 'Mario Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dhruv/terraform'
    backendServiceArm: 'padawans-azure'
    backendAzureRmResourceGroupName: 'gft-rg-padawans'
    backendAzureRmStorageAccountName: 'gftstpadawantfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.Dhruv.tfstate'


# (3) Create a 'Terraform Validate' task
- task: TerraformTaskV2@2
  displayName: 'Mario Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dhruv/terraform'
    environmentServiceNameAzureRM: 'padawans-azure'


# (4) Create a 'Terraform Plan' task
# Additional Command Arguments: -out=tfplan
- task: TerraformTaskV2@2
  displayName: 'Mario Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dhruv/terraform'
    environmentServiceNameAzureRM: 'padawans-azure'
    commandOptions: '-out=tfplan'



# (5) Create a 'Terraform Apply' task
# Additional Command Arguments: tfplan
- task: TerraformTaskV2@2
  displayName: 'Mario Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dhruv/terraform'
    environmentServiceNameAzureRM: 'padawans-azure'
    commandOptions: 'tfplan'