# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04' #ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo '%CD%'' '%CD' ""
      
      echo Hello world

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo '%CD%'
      echo 'pwd'
      echo '%pwd%'
      
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '/padawan/Sam/pipelines-dotnet-core-master/pipelines-dotnet-core.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need


#build ../padawan/Sam/pipelines-dotnet-core-master/pipelines-dotnet-core.csproj