# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04' #ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- script: dotnet build pipelines-dotnet-core-master/pipelines-dotnet-core.csproj --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: pipelines-dotnet-core-master/pipelines-dotnet-core.csproj'#'../padawan/Sam/pipelines-dotnet-core-master/pipelines-dotnet-core.csproj'
