# Starter Terraform pipeline
# Start with a minimal Terraform pipeline that you can customize to build and deploy your infrastructure.

# Change the pipeline name
name: terraform-?-pipeline

variables:
  - name: ServiceConnection
    value: padawans-gcp

# Customize paths:include: to only detect changes in your folder
trigger:
  branches:
    include:
      - master
  paths:
    include: 
      - {your_name}/terraform

pool:
  vmImage: ubuntu-latest

steps:

# Create a 'Install Terraform' task
# Parameters:
# - Version = 1.0.1

# Create a 'Terraform Init' task
# Parameters:
# - Azure Subscription = padawans-azure
# - Resource Group: gft-rg-padawans
# - Storage Account: gftstpadawantfstate
# - Storage Container: tfstate
# - Key: terraform.{your_name}.tfstate

# Create a 'Terraform Validate' task

# Create a 'Terraform Plan' task
# Additional Command Arguments: -out=tfplan

# Create a 'Terraform Apply' task
# Additional Command Arguments: tfplan

